default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: MyPassword

development:
  <<: *default
  database: recipe_api_development
  host: localhost
  username: postgres
  password: MyPassword

test:
  <<: *default
  database: recipe_api_test
  host: localhost
  username: postgres
  password: MyPassword

production:
  <<: *default
  database: recipe_api_production
  username: recipe_api
  password: <%= ENV["RECIPE_API_DATABASE_PASSWORD"] %>

